apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-feedback-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::820198199907:role/flask-feedback-s3-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-feedback-app
  labels:
    app: flask-feedback-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-feedback-app
  template:
    metadata:
      labels:
        app: flask-feedback-app
    spec:
      serviceAccountName: flask-feedback-sa
      containers:
      - name: flask
        image: 820198199907.dkr.ecr.us-east-1.amazonaws.com/flask-feedback-app:v2
        ports:
        - containerPort: 5000
        env:
        - name: FEEDBACK_BUCKET
          value: "feedback-app-submissions-l00203120"
        - name: SECRET_KEY
          value: "production-secret"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
